
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int palavra_not = 14;
  public static final int palavra_and = 15;
  public static final int palavra_procedure = 16;
  public static final int OPSUB = 24;
  public static final int palavra_while = 6;
  public static final int NUM_INT = 20;
  public static final int DESCONHECIDO = 37;
  public static final int palavra_program = 12;
  public static final int DOIS_PONTOS = 19;
  public static final int FIM = 23;
  public static final int VIRGULA = 17;
  public static final int IDENTIFICADOR = 36;
  public static final int tipo_boolean = 11;
  public static final int FP = 28;
  public static final int palavra_or = 13;
  public static final int palavra_else = 4;
  public static final int OP_DIF = 35;
  public static final int palavra_if = 2;
  public static final int EOF = 0;
  public static final int palavra_then = 3;
  public static final int tipo_int = 10;
  public static final int PONTO_VIRGULA = 18;
  public static final int error = 1;
  public static final int palavra_end = 9;
  public static final int OPDIV = 26;
  public static final int NUM_REAL = 21;
  public static final int palavra_var = 7;
  public static final int OP_IGUAL = 34;
  public static final int OPMUL = 25;
  public static final int OP_MENOR_IGUAL = 31;
  public static final int palavra_begin = 8;
  public static final int OP_MAIOR_IGUAL = 32;
  public static final int OP_ATRI = 33;
  public static final int OP_MAIOR = 30;
  public static final int AP = 27;
  public static final int OP_MENOR = 29;
  public static final int OPSOMA = 22;
  public static final int palavra_do = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "palavra_if",
  "palavra_then",
  "palavra_else",
  "palavra_do",
  "palavra_while",
  "palavra_var",
  "palavra_begin",
  "palavra_end",
  "tipo_int",
  "tipo_boolean",
  "palavra_program",
  "palavra_or",
  "palavra_not",
  "palavra_and",
  "palavra_procedure",
  "VIRGULA",
  "PONTO_VIRGULA",
  "DOIS_PONTOS",
  "NUM_INT",
  "NUM_REAL",
  "OPSOMA",
  "FIM",
  "OPSUB",
  "OPMUL",
  "OPDIV",
  "AP",
  "FP",
  "OP_MENOR",
  "OP_MAIOR",
  "OP_MENOR_IGUAL",
  "OP_MAIOR_IGUAL",
  "OP_ATRI",
  "OP_IGUAL",
  "OP_DIF",
  "IDENTIFICADOR",
  "DESCONHECIDO"
  };
}

